### ISSUE TITLE
Decouple from Bevy

### ISSUE THREAD

**Issue by UkoeHB** [DrewRidley/nevy#2]
The WebTransport implementation is tightly coupled to Bevy in `update_endpoints`. I'm interested in using this library to replace the `renet2` WebTransport implementation, but need to use it in non-Bevy context. Can you wrap the APIs in an abstraction layer (e.g. higher-level resource)?

**Comment by DrewRidley** [comment]
Hi, thanks for your interest in my work.

The transport layer is currently pending a major refactor that will be done in the next few days. During this major refactor we will be sure to fully detach the endpoint from bevy events. The endpoint will also more than likely be a trait so the browser/wasm interface has the same api as the native one.

I will keep you posted and appreciate your suggestion.

**Comment by DrewRidley** [comment]
Hello @UkoeHB,

I am happy to announce the refactor was completed. The implementation is no longer dependent on bevy at all. If you want to use standard QUIC protocol, feel free to use ``nevy_quic``, but if you require WebTransport headers and negotiation, ``nevy_web_transport`` should do the trick.

Let me know if you have any questions.
